/* Populate tabla clientes */
INSERT INTO clientes (nombre,apellido,email,create_at) VALUES('Fran','García','fran@iessanvicente.es','2019-11-29');
INSERT INTO clientes (nombre,apellido,email,create_at) VALUES('Juan','García','juan@iessanvicente.es','2016-12-09');
INSERT INTO clientes (nombre,apellido,email,create_at) VALUES('Oleksandr','Naumov','olek@iessanvicente.es','2012-11-29');
INSERT INTO clientes (nombre,apellido,email,create_at) VALUES('Miguel','Klitchko','miguel@iessanvicente.es','2010-01-19');
INSERT INTO clientes (nombre,apellido,email,create_at) VALUES('Evaristo','Peñon','ever@iessanvicente.es','2020-01-12');
INSERT INTO clientes (nombre,apellido,email,create_at) VALUES('John','Johnson','john@iessanvicente.es','2019-03-02');
INSERT INTO clientes (nombre,apellido,email,create_at) VALUES('Guillermo','Gonzalez','gg@iessanvicente.es','2010-01-09');
INSERT INTO clientes (nombre,apellido,email,create_at) VALUES('Amon','Love','love@iessanvicente.es','2015-05-09');
INSERT INTO clientes (nombre,apellido,email,create_at) VALUES('Sergio','Pardo','spar@iessanvicente.es','2015-08-10');