// default package
// Generated 29-ene-2020 16:05:53 by Hibernate Tools 5.4.7.Final
package com.fran.eoihibernate2;
import java.util.HashSet;
import java.util.Set;

/**
 * Autores generated by hbm2java
 */
public class Autores implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String cod;
	private String nombre;
	private Set<Libros> libros = new HashSet<Libros>(0);

	public Autores() {
	}

	public Autores(String cod) {
		this.cod = cod;
	}

	public Autores(String cod, String nombre, Set<Libros> libros) {
		this.cod = cod;
		this.nombre = nombre;
		this.libros = libros;
	}

	public String getCod() {
		return this.cod;
	}

	public void setCod(String cod) {
		this.cod = cod;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Libros> getLibros() {
		return this.libros;
	}

	public void setLibros(Set<Libros> libros) {
		this.libros = libros;
	}

}
