package com.oleksandr.hibernateej2;

// default package
// Generated 31-ene-2020 18:11:24 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Actores generated by hbm2java
 */
public class Actores implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String nombre;
	private String apellidos;
	private Set<Series> serieses = new HashSet<Series>(0);

	public Actores() {
	}

	public Actores(int id) {
		this.id = id;
	}

	public Actores(int id, String nombre, String apellidos, Set<Series> serieses) {
		this.id = id;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.serieses = serieses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Set<Series> getSerieses() {
		return this.serieses;
	}

	public void setSerieses(Set<Series> serieses) {
		this.serieses = serieses;
	}

}
