package com.oleksandr.hibernateej2;

// default package
// Generated 31-ene-2020 18:11:24 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cadenas generated by hbm2java
 */
public class Cadenas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String cod;
	private String nombre;
	private Set<Cadenas> serieses = new HashSet<Cadenas>(0);

	public Cadenas() {
	}

	public Cadenas(String cod) {
		this.cod = cod;
	}

	public Cadenas(String cod, String nombre, Set<Cadenas> serieses) {
		this.cod = cod;
		this.nombre = nombre;
		this.serieses = serieses;
	}

	public String getCod() {
		return this.cod;
	}

	public void setCod(String cod) {
		this.cod = cod;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Cadenas> getSerieses() {
		return this.serieses;
	}

	public void setSerieses(Set<Cadenas> serieses) {
		this.serieses = serieses;
	}

}
