package com.oleksandr.hibernateej2;

// default package
// Generated 31-ene-2020 18:11:24 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Series generated by hbm2java
 */
public class Series implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int codSeries;
	private Cadenas cadenas;
	private String nombre;
	private Integer duracion;
	private Set<Actores> actoreses = new HashSet<Actores>(0);

	public Series() {
	}

	public Series(int codSeries) {
		this.codSeries = codSeries;
	}

	public Series(int codSeries, Cadenas cadenas, String nombre, Integer duracion, Set<Actores> actoreses) {
		this.codSeries = codSeries;
		this.cadenas = cadenas;
		this.nombre = nombre;
		this.duracion = duracion;
		this.actoreses = actoreses;
	}

	public int getCodSeries() {
		return this.codSeries;
	}

	public void setCodSeries(int codSeries) {
		this.codSeries = codSeries;
	}

	public Cadenas getCadenas() {
		return this.cadenas;
	}

	public void setCadenas(Cadenas cadenas) {
		this.cadenas = cadenas;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Integer getDuracion() {
		return this.duracion;
	}

	public void setDuracion(Integer duracion) {
		this.duracion = duracion;
	}

	public Set<Actores> getActoreses() {
		return this.actoreses;
	}

	public void setActoreses(Set<Actores> actoreses) {
		this.actoreses = actoreses;
	}

}
